### ISSUE TITLE
메인페이지 - Footer 디자인

### ISSUE THREAD

**Issue by ppochaco** [KNU-HAEDAL-Website/frontend-v1#40]
## Description

> footer mobile size ui 깨짐

## When does it happen?

> 화면의 width가 작아질 때마다 footer의 컴포넌트의 크기가 깨집니다,

## Expected result

> 각 컴포넌트의 css를 absoulte 대신 flex로 변경하기

**Comment by Dobbymin** [comment]
flex로 변경하면 되는군요.. 감사합니다!

**Comment by ppochaco** [comment]
flex-wrap 사용해보세용,,,
